+ run minibat
Ryu204/tiny-shell pull request #14
Opened 2024-03-17 00:50 UTC by bin1st090104

2024-03-17 08:41 UTC, Ryu204 requested changes

2024-03-17 08:41 UTC, Ryu204 commented on source/core/args.c
> -    res->argv[res->argc] = NULL;
Vì răng m xóa argv[argc]=NULL rứa?

2024-03-17 08:41 UTC, Ryu204 commented on source/core/cmd.c
> +            }
dùng hàm args_deep_copy để giảm lặp code

2024-03-17 08:41 UTC, Ryu204 commented on source/os/operations_win.c
> +    const os_char *backslash = strrchr(path, '\\');
cách này k portable. t nghĩ hàm get_file_extension có thể được cài đặt mà k cần hàm này

2024-03-17 08:41 UTC, Ryu204 commented on source/os/operations_win.c
> +    const os_char *dot = strrchr(filename, '.');
cái này hình như fail với trường hợp `abc.xyz.mb` hè

2024-03-17 08:54 UTC, Ryu204 commented on source/os/operations_win.c
> +        return false;
mất file handle

2024-03-17 13:52 UTC, Ryu204 commented on source/os/operations_win.c
> +    const os_char *dot = strrchr(filename, '.');
sorry m :'> t nhầm `strch` với `strrchr` m ả. lần sau t sẽ test kị đạ r comment

2024-03-17 13:54 UTC, Ryu204 commented on source/os/operations_win.c
> +    const os_char *dot = strrchr(filename, '.');
chắc là dùng `strrchr` thẳng luôn chứ k tách tên file đã cũng được nhỉ

2024-03-17 14:06 UTC, bin1st090104 commented on source/os/operations_win.c
> +    const os_char *dot = strrchr(filename, '.');
> chắc là dùng `strrchr` thẳng luôn chứ k tách tên file đã cũng được nhỉ

Thì cũng phải xác định điểm bắt đầu của tên file vì có thể tên file ko có extension mà trong đường dẫn lại có dot

2024-03-17 14:22 UTC, bin1st090104 commented on source/core/args.c
> -    res->argv[res->argc] = NULL;
1 là thừa 2 là trong hàm destroy ko có xử lý

2024-03-17 14:22 UTC, Ryu204 commented on source/core/cmd.c
> +            free(args);
t nghị chỗ ni k có `free` mô m, hấn được free qua hàm `cmd_destroy` trong `main` á

2024-03-17 14:24 UTC, Ryu204 commented on source/core/args.c
> -    res->argv[res->argc] = NULL;
k thừa mô m ơi, trong linux hấn yêu cầu mảng argv phải có phần tử cuối là NULL

trong destroy khi ta gọi `free(argv)` là hấn xóa hết tất cả những chỗ đã malloc/realloc luôn. với lại chỗ ni t check bằng valgrind nên chắc k bị leak :'>

2024-03-17 14:25 UTC, Ryu204 commented on source/os/operations_win.c
> +    const os_char *dot = strrchr(filename, '.');
đưa một vd được không m

2024-03-17 14:29 UTC, bin1st090104 commented on source/core/cmd.c
> +            free(args);
đây là free con trỏ struct args đc tạo ra bởi hàm args_deep_copy còn cmd_destroy là free mội dung của struct args mà nhỉ

2024-03-17 14:32 UTC, bin1st090104 commented on source/core/args.c
> -    res->argv[res->argc] = NULL;
:v ra vậy ✌️

2024-03-17 14:40 UTC, bin1st090104 commented on source/os/operations_win.c
> +    const os_char *dot = strrchr(filename, '.');
build.conf/test

2024-03-17 15:50 UTC, Ryu204 commented on source/os/operations_win.c
> +    const os_char *dot = strrchr(filename, '.');
nếu rứa thì khi check `dot==mb` hấn sẽ trả về `false` nên vẫn ok

2024-03-17 15:54 UTC, Ryu204 commented on source/core/cmd.c
> +            free(args);
`free(con trỏ)` là giải phóng vùng nhớ được tạo từ cấp phát động chứ

ô nhớ mà `struct args *args` trỏ đến được tạo từ `malloc` nên khi gọi free như thế nó sẽ free ô nhớ chứa giá trị luôn

còn bản thân `args` là con trỏ có địa chỉ trên stack nên xong hàm thì bị xóa

2024-04-10 15:31 UTC, Ryu204 requested changes

2024-04-10 15:31 UTC, Ryu204 commented on source/core/cmd.c
> +            res->val.args = *args;
Chỗ này mem leak thì phải, do `args` chưa được `free`

2024-04-10 15:31 UTC, Ryu204 commented on source/runner/invoke.c
> +        return run_minibat(cmd->val.args);
Cái này t nghĩ nếu tạo thêm 1 member trong union `cmd` là `filename` thì hợp lý hơn, do trước đó m cũng check `cmd->val.args.argc == 1`. Mà để như thế này người khác đọc không rõ ý đồ.

2024-04-11 15:11 UTC, bin1st090104 commented on source/runner/invoke.c
> +        return run_minibat(cmd->val.args);
còn p dùng args.background nữa mà

2024-04-12 09:51 UTC, Ryu204 commented on source/runner/invoke.c
> +        return run_minibat(cmd->val.args);
à okay, t không để ý

2024-04-12 10:11 UTC, Ryu204 approved these changes

2024-04-12 10:12 UTC, merged